// Generated by CoffeeScript 1.4.0

(function() {
  var CsrfCtrl, angular, root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  angular = root.angular;

  CsrfCtrl = function($cookieStore) {
    return $cookieStore.put("XSRF-TOKEN", angular.element(document.getElementById("csrf")).attr("data-csrf"));
  };

  CsrfCtrl.$inject = ['$cookieStore'];

  root.CsrfCtrl = CsrfCtrl;

}).call(this);
