// Generated by CoffeeScript 1.4.0
(function() {
  var CsrfCtrl, root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  CsrfCtrl = [
    "$cookieStore", function($cookieStore) {
      return $cookieStore.put("XSRF-TOKEN", angular.element(document.getElementById("csrf")).attr("data-csrf"));
    }
  ];
  // exports
  root.CsrfCtrl = CsrfCtrl;

}).call(this);
