// Generated by CoffeeScript 1.4.0
(function() {
  var WelcomeCtrl, root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  WelcomeCtrl = ["$scope", function($scope) {}];

  // exports
  root.thisApp.controller("WelcomeCtrl", WelcomeCtrl);

}).call(this);
