// Generated by CoffeeScript 1.4.0
(function() {
  var root, thisApp;

  root = typeof global !== "undefined" && global !== null ? global : window;

  thisApp = root.thisApp;

  thisApp.controller("WelcomeCtrl", function() {});

}).call(this);
