// Generated by CoffeeScript 1.4.0
(function() {
  var WelcomeCtrl, root;

  root = typeof global !== "undefined" && global !== null ? global : window;

  WelcomeCtrl = function($scope) {};

  WelcomeCtrl.$inject(['$scope']);

  root.thisApp.controller("WelcomeCtrl", WelcomeCtrl);

}).call(this);
